resource "aws_launch_template" "launchtemplate-schaffnerkelian" {                                                                                                  # Déclare une ressource de type 'aws_launch_template' avec le nom 'launchtemplate-schaffnerkelian'
  name          = "launchtemplateschaffnerkelian"                                                                                                                  # Attribue le nom 'launchtemplateschaffnerkelian' à ce modèle de lancement
  image_id      = "ami-012ba92271e91512d"                                                                                                                          # Spécifie l'ID de l'image AMI à utiliser pour le lancement
  instance_type = "t2.micro"                                                                                                                                       # Spécifie le type d'instance à lancer
  key_name      = aws_key_pair.deployer-key-schaffnerkelian.key_name                                                                                               # Spécifie la paire de clés à utiliser pour l'instance
  network_interfaces {                                                                                                                                             # Définit les interfaces réseau pour l'instance
    associate_public_ip_address = true                                                                                                                             # Spécifie que l'instance doit avoir une adresse IP publique
    delete_on_termination       = true                                                                                                                             # Spécifie que l'interface réseau doit être supprimée lorsque l'instance est terminée
    security_groups             = ["sg-04891020a5d7968f5", aws_security_group.sg_app_to_lb_schaffnerkelian.id, aws_security_group.sg_lb_to_app_schaffnerkelian.id] # Spécifie les groupes de sécurité à associer à l'interface réseau
  }
  user_data = base64encode("#!/bin/bash\ncd /home/ubuntu/app/\nsudo docker compose up --build -d") # Spécifie les données utilisateur à passer à l'instance lors du lancement
  placement {                                                                                      # Spécifie le placement de l'instance
    availability_zone = "eu-west-1a"                                                               # Spécifie la zone de disponibilité pour l'instance
  }
}

resource "aws_key_pair" "deployer-key-schaffnerkelian" {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Déclare une ressource de type 'aws_key_pair' avec le nom 'deployer-key-schaffnerkelian'
  key_name   = "deployer-key-schaffnerkelian"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   # Attribue le nom 'deployer-key-schaffnerkelian' à cette paire de clés
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRCa4+uW8BoBOiYFzhkdg4cE6906IlY5aWCX3OsebN4rta9m6Uz3e07UUNXZny3FC1F3e5sVrCwZb3ZGXVvSSDthKizmRKlGmjF/qXySK9wOizxKLo6mPfcZkBUv9cqEuMlss7cR+tLlAhTrLYZywgWzuJdGNqmUm8wGd2u8anBlwbasLH5vbjkETtMvPK6ObQJRVhB1SccnWoHg67TzHp5TtCnmms151F/6O3to6L0wZNCpGC4P0WBMbGZWfd2pp+GOmHlgj9QOrITudR+TWMPUswWQhwEZglvAhKctrG8fbiwMezBjVZn1n/mo9GnzaD7LTc7BdN043t18n2cgt/zBoFAAjqA4U+SOi2igmbP5RNSjLq0ynT24hC3xxJn1rTjsJynJOnhUnNm1ffzQM8oicT/uU1vXhPTqIwGZT9mladjWYq7yQXh7tJiMNSrBgAGc7cL8s30ADM2hnCi61o3usOPv6mdpN/aOWJAYsl24II8h4KbtzLz5RAc496eus= schaf@DESKTOP-AEJ9M2Q" # Spécifie la clé publique pour cette paire de clés
}
